# Generated by Django 3.2.12 on 2022-02-12 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Buses', '0002_auto_20220212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bus_route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Buses.busroute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='station_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_end', to='Buses.station'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='station_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_start', to='Buses.station'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buses.registrationperiodtype'),
        ),
    ]
