# Generated by Django 3.2.12 on 2022-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_auto_20220213_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='recide_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
